window.stakeData = {
  isLay: false,
  sum: 0,
  laySum: 0,
  liability: 0,
  balanceBeforeStake: 0,
  balanceBeforeCancel: 0,
  cancelSum: 0,
  layCancelSum: 0,
  isFake: false,
  fakeReloaded: false,
  fakeSum: 0,
  fakeCoefficient: 0,
  fakeEvent: '',
  fakeBetName: '',
  stakePlaced: false,
  rawCoefficient: 0,
  layCoefficient: 0,
  realCoefficient: 0,
  enabled: true,
  isNewBetslip: false,
  isCancelling: false,
  isCancelled: false,
  isCheckDelayed: false,
};
